version: '3.3'
services:
  postgres:
    image: postgres:12
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 5432
    volumes:
      - type: bind
        source: ./build/
        target: /data
